### ISSUE TITLE
read the configuration file

### ISSUE THREAD

**Issue by mohammedi-haroune** [mohammedi-haroune/ai-player-conf#1]
- [x] we should be able to read the hocon configuration file using pyhcon and visualize them to a web UI
the configuration file template is as follows :
```
gestures = ["stop", "point1", "point2", "fist", "grab"]
actions = [
    "com.usthb.ai.player.Start",
    "com.usthb.ai.player.Pause",
    "com.usthb.ai.player.Resume",
    "com.usthb.ai.player.Play",
    "com.usthb.ai.player.Abort",
    "com.usthb.ai.player.Seek",
    "com.usthb.ai.player.RevertSeek",
    "com.usthb.ai.player.PlayListNext",
    "com.usthb.ai.player.PlayListPrev",
    "com.usthb.ai.player.VolumeUp",
    "com.usthb.ai.player.VolumeDown",
    "com.usthb.ai.player.SpeedUp",
    "com.usthb.ai.player.SpeedDown",
    "com.usthb.ai.player.None"
]

aborted {
  stop = "com.usthb.ai.player.None"
  fist = "com.usthb.ai.player.Start"
  point1 = "com.usthb.ai.player.None"
  point2 = "com.usthb.ai.player.None"
  grab = "com.usthb.ai.player.None"
}

paused {
  stop = "com.usthb.ai.player.Resume"
  fist = "com.usthb.ai.player.Abort"
  point1 = "com.usthb.ai.player.VolumeUp"
  point2 = "com.usthb.ai.player.VolumeDown"
  grab = "com.usthb.ai.player.PlayListNext"
}

playing {
  stop = "com.usthb.ai.player.Pause"
  fist = "com.usthb.ai.player.Abort"
  point1 = "com.usthb.ai.player.SpeedUp"
  point2 = "com.usthb.ai.player.SpeedDown"
  grab = "com.usthb.ai.player.PlayListPrev"
}
```
- [x] we should also ensure that you can change those values after reading them
- [x] we should write the new changed configuration to a external file

**Comment by mohammedi-haroune** [comment]
Here are the pics to use for action illustration
![stop](https://user-images.githubusercontent.com/23096288/39594913-dfdac870-4f05-11e8-9bf8-4d5d0c0d2cc2.jpg)
![point2](https://user-images.githubusercontent.com/23096288/39594914-e000a702-4f05-11e8-9101-2bfea6202d9e.jpg)
![point1](https://user-images.githubusercontent.com/23096288/39594916-e0683fac-4f05-11e8-97cb-2c9804618d41.jpg)
![grab](https://user-images.githubusercontent.com/23096288/39594917-e0935804-4f05-11e8-86ff-9c1ac368ec03.jpg)
![fist](https://user-images.githubusercontent.com/23096288/39594919-e0d1be96-4f05-11e8-96b7-f8c52650ecf2.jpg)

**Comment by ghost** [comment]
It's done, baby

**Comment by mohammedi-haroune** [comment]
@TahaMohammedi Great job, I really appretiate it :+1:

**Comment by ghost** [comment]
I'm sure you are #
