### ISSUE TITLE
user experience improvement suggestions

### ISSUE THREAD

**Issue by mohammedi-haroune** [mohammedi-haroune/ai-player-conf#4]
After using the app i found some drawbacks in terms of user experience, I think following points should be reviewed : 
1. don't refresh after saving, just notify the use with something like **changes made successfully**
2. consider another layout for organizing the components (images, combo boxes ... etc)
    - The show / hide button is just annoying me, why we don't just have 
    - Put gesture labels under images, it's too big I think
3. we should be able to select the configuration file, it's not necessary in the current directory

Those are some feedback after trying to use the app, theses aren't bugs or problems but just some suggestions from a simple user.

**Comment by ghost** [comment]
It's done, baby
